### ISSUE TITLE
Example how to use?

### ISSUE THREAD

**Issue by isAlmogK** [adam12/phoenix_mtm#15]
Do you have a simple example showing code how to use this

**Comment by adam12** [comment]
There are some examples in the builtin documentation, and both parts (the HTML helper and the Ecto component) are tested in `tests/` which translates over to your application, mostly.

I purposely left the Usage section in the README vague as an example would end of spanning multiple files and I don't think it would make things any clearer.

I'd be open to a PR that would improve this, if it does indeed make things clearer.

**Comment by fceruti** [comment]
Hello @adam12 , thanks for sharing your work 😀 

I've been trying to follow the examples in the documentation but I can't seem to get it right.

In particular I would like to know see how you build the Changeset so that I don't get an `protocol Enumerable not implemented for #Ecto.Association.NotLoaded` error in [this line].(https://github.com/adam12/phoenix_mtm/blob/master/lib/phoenix_mtm/helpers.ex#L17).

To me, an example controller or LiveView would seal the deal.

**Comment by adam12** [comment]
Hi @fceruti,

I'm no longer writing Elixir, so I'd be unable to help with an example as it's been some time since I've had to use it. As far as I know, PhoenixMTM still works with Phoenix/Ecto today, and I would accept a bug report / fix if it wasn't.

The error you have sounds like Ecto preventing an N+1 query. Perhaps start there, or post to the Elixir Forum?

I'm sorry I can't be more help.
